[package]
name = "pgn_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgn-reader = "0.19.0"
shakmaty = "0.20.7"
lazy_static = "1.4.0"
regex = "1.5"
